language: node_js
before_script:
  - sleep 10
cache:
  directories:
    - ~/.npm
notifications:
  email: false
before_install:
  - npm install -g npm gally
  - ga promote $TRAVIS_BRANCH
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.3.0.deb && sudo dpkg -i --force-confnew elasticsearch-6.3.0.deb && sudo service elasticsearch start
install:
  - npm install
node_js:
  - '10'
  - '8.10'
script:
  - npm test
after_success:
  - npm run coveralls
  - npm run semantic-release
