language: node_js
sudo: false
cache:
  directories:
    - ~/.npm
notifications:
  email: false
addons:
  apt:
    sources:
      - elasticsearch-6.3
    packages:
      - elasticsearch
services:
  - elasticsearch
before_install:
  - npm install -g npm gally
  - ga promote $TRAVIS_BRANCH
install:
  - npm install
node_js:
  - '10'
  - '8.10'
before_script:
  - echo 'waiting for elasticsearch to come up'; wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
script:
  - npm test
after_success:
  - npm run coveralls
  - npm run semantic-release
