workflows:
  version: 2
  node-multi-build:
    jobs:
      - gally
      - test-node-v10
      - test-node-v8.10
      - release:
          requires:
            - gally
            - test-node-v10
            - test-node-v8.10
          filters:
            branches:
              only: master
version: 2
jobs:
  gally:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - run: sudo npm i -g gally
      - run: ga promote $CIRCLE_BRANCH
  test-node-v10:
    docker:
      - image: 'circleci/node:10'
        environment:
          elasticsearchEndpoint: 'localhost:9200'
      - image: 'docker.elastic.co/elasticsearch/elasticsearch:6.3.0'
        environment:
          - discovery.type=single-node
          - http.host=0.0.0.0
          - transport.host=127.0.0.1
          - xpack.security.enabled=false
          - ES_JAVA_OPTS=-Xms750m -Xmx750m
    steps:
      - checkout
      - run: npm i
      - run: npm t
  test-node-v8.10:
    docker:
      - image: 'circleci/node:8.10'
        environment:
          elasticsearchEndpoint: 'localhost:9200'
      - image: 'docker.elastic.co/elasticsearch/elasticsearch:6.3.0'
        environment:
          - discovery.type=single-node
          - http.host=0.0.0.0
          - transport.host=127.0.0.1
          - xpack.security.enabled=false
          - ES_JAVA_OPTS=-Xms750m -Xmx750m
    steps:
      - checkout
      - run: npm i
      - run: npm t
  release:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - run: npm i
      - run: npm run coveralls
      - run: npm run semantic-release
